export const PROJECT_FORM_WIDTH = 520;
export const PROJECT_TAB_WIDTH = 80;
export const PROJECT_TAB_HEIGHT = 32;
export const PROJECT_CHIP_WIDTH = PROJECT_TAB_WIDTH;
export const PROJECT_CHIP_HEIGHT = PROJECT_TAB_HEIGHT;
