export const PROJECT_FORM_WIDTH = 520;
export const PROJECT_HISTORY_CHIP_WIDTH = 80;
export const PROJECT_HISTORY_CHIP_HEIGHT = 32;
export const PROJECT_CHIP_WIDTH = PROJECT_HISTORY_CHIP_WIDTH;
export const PROJECT_CHIP_HEIGHT = PROJECT_HISTORY_CHIP_HEIGHT;
