export const TRUE_TOS_CHECKED_STATE = {
	ALL: true,
	REQUIRED: true,
	PERSONAL_INFORMATION: true,
	SHOPPING_INFORMATION_RECEIPT: true,
};

export const FALSE_TOS_CHECKED_STATE = {
	ALL: false,
	REQUIRED: false,
	PERSONAL_INFORMATION: false,
	SHOPPING_INFORMATION_RECEIPT: false,
};
