export type InstatoonCategoryType =
	| "EVERYDAY_HEALING"
	| "ACTION"
	| "HISTORICAL_DRAMA"
	| "HUMOR"
	| "THRILLER"
	| "FASHION"
	| "EMPATHY"
	| "EPISODE"
	| "ROMANCE"
	| "SF"
	| "HORROR"
	| "SADNESS"
	| "SPORTS"
	| "TOUCHING_DRAMA";
